export const SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS app_schema_migrations (
    migration_key VARCHAR(120) NOT NULL PRIMARY KEY,
    applied_at DATETIME(3) NOT NULL,
    details VARCHAR(500) NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_users (
    id CHAR(36) NOT NULL PRIMARY KEY,
    username VARCHAR(32) NOT NULL,
    username_key VARCHAR(64) NOT NULL,
    password_salt VARCHAR(128) NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    nickname VARCHAR(40) NULL,
    admin_note VARCHAR(500) NULL,
    must_change_password TINYINT(1) NOT NULL DEFAULT 0,
    role ENUM('admin','user') NOT NULL DEFAULT 'user',
    status ENUM('pending','active','disabled','rejected') NOT NULL DEFAULT 'pending',
    created_at DATETIME(3) NOT NULL,
    approved_at DATETIME(3) NULL,
    last_login_at DATETIME(3) NULL,
    last_active_at DATETIME(3) NULL,
    credit_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
    UNIQUE KEY uq_app_users_username_key (username_key),
    KEY idx_app_users_status_created (status, created_at),
    KEY idx_app_users_role (role)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_sessions (
    token_hash CHAR(64) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    KEY idx_app_sessions_user (user_id),
    KEY idx_app_sessions_expires (expires_at),
    CONSTRAINT fk_app_sessions_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_login_records (
    id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NULL,
    username VARCHAR(32) NOT NULL,
    success TINYINT(1) NOT NULL,
    reason VARCHAR(300) NULL,
    created_at DATETIME(3) NOT NULL,
    client_ip VARCHAR(120) NULL,
    user_agent VARCHAR(600) NULL,
    KEY idx_app_login_user_created (user_id, created_at),
    KEY idx_app_login_created (created_at),
    CONSTRAINT fk_app_login_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_usage_records (
    id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    username VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    provider VARCHAR(80) NOT NULL,
    model VARCHAR(160) NOT NULL,
    operation ENUM('text-to-image','image-edit') NOT NULL,
    size VARCHAR(80) NOT NULL,
    prompt TEXT NULL,
    image_count INT UNSIGNED NOT NULL DEFAULT 0,
    status ENUM('success','submitted','failed') NOT NULL,
    duration_ms BIGINT UNSIGNED NULL,
    cost DECIMAL(18,6) NULL,
    request_id VARCHAR(200) NULL,
    operation_id VARCHAR(200) NULL,
    points_cost_cents BIGINT UNSIGNED NULL,
    points_refunded TINYINT(1) NOT NULL DEFAULT 0,
    error VARCHAR(800) NULL,
    KEY idx_app_usage_user_created (user_id, created_at),
    KEY idx_app_usage_status_created (status, created_at),
    KEY idx_app_usage_request (user_id, request_id),
    KEY idx_app_usage_operation (operation_id),
    CONSTRAINT fk_app_usage_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_generation_tasks (
    id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    provider VARCHAR(80) NOT NULL,
    model VARCHAR(160) NOT NULL,
    operation ENUM('text-to-image','image-edit') NOT NULL,
    size VARCHAR(80) NOT NULL,
    prompt TEXT NULL,
    status ENUM('queued','running','success','failed','cancelled') NOT NULL DEFAULT 'queued',
    task_stage VARCHAR(40) NOT NULL DEFAULT 'queued',
    progress TINYINT UNSIGNED NOT NULL DEFAULT 5,
    requested_image_count INT UNSIGNED NOT NULL DEFAULT 1,
    actual_image_count INT UNSIGNED NOT NULL DEFAULT 0,
    operation_id VARCHAR(200) NULL,
    provider_task_id VARCHAR(200) NULL,
    usage_record_id CHAR(36) NULL,
    history_id CHAR(36) NULL,
    reserved_points_cents BIGINT UNSIGNED NULL,
    actual_points_cents BIGINT UNSIGNED NULL,
    refunded_points_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
    request_snapshot JSON NULL,
    thumbnail_data_url LONGTEXT NULL,
    provider_progress VARCHAR(300) NULL,
    error_code VARCHAR(100) NULL,
    error_message VARCHAR(800) NULL,
    retry_from_task_id CHAR(36) NULL,
    created_at DATETIME(3) NOT NULL,
    started_at DATETIME(3) NULL,
    updated_at DATETIME(3) NOT NULL,
    completed_at DATETIME(3) NULL,
    KEY idx_app_tasks_user_created (user_id, created_at),
    KEY idx_app_tasks_status_updated (status, updated_at),
    KEY idx_app_tasks_provider_task (user_id, provider_task_id),
    KEY idx_app_tasks_operation (user_id, operation_id),
    KEY idx_app_tasks_history (history_id),
    CONSTRAINT fk_app_tasks_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_recharge_cards (
    id CHAR(36) NOT NULL PRIMARY KEY,
    code_hash CHAR(64) NOT NULL,
    code_preview VARCHAR(80) NOT NULL,
    credit_cents BIGINT UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL,
    created_by VARCHAR(32) NOT NULL,
    redeemed_at DATETIME(3) NULL,
    redeemed_by_user_id CHAR(36) NULL,
    redeemed_by_username VARCHAR(32) NULL,
    UNIQUE KEY uq_app_cards_code_hash (code_hash),
    KEY idx_app_cards_created (created_at),
    KEY idx_app_cards_redeemed (redeemed_at),
    KEY idx_app_cards_redeemed_user (redeemed_by_user_id),
    CONSTRAINT fk_app_cards_redeemed_user FOREIGN KEY (redeemed_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_credit_transactions (
    id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    username VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    type ENUM('generation_charge','generation_refund','card_recharge','admin_adjustment') NOT NULL,
    amount_cents BIGINT NOT NULL,
    balance_after_cents BIGINT UNSIGNED NOT NULL,
    note VARCHAR(300) NULL,
    provider VARCHAR(80) NULL,
    model VARCHAR(160) NULL,
    reference_id VARCHAR(200) NULL,
    card_id CHAR(36) NULL,
    actor_user_id CHAR(36) NULL,
    KEY idx_app_credit_user_created (user_id, created_at),
    KEY idx_app_credit_reference (reference_id),
    UNIQUE KEY uq_app_credit_type_reference (type, reference_id),
    CONSTRAINT fk_app_credit_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_credit_card FOREIGN KEY (card_id) REFERENCES app_recharge_cards(id) ON DELETE SET NULL,
    CONSTRAINT fk_app_credit_actor FOREIGN KEY (actor_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_history_records (
    id CHAR(36) NOT NULL PRIMARY KEY,
    owner_user_id CHAR(36) NULL,
    client_id VARCHAR(160) NULL,
    generation_task_id CHAR(36) NULL,
    provider VARCHAR(80) NOT NULL,
    provider_name VARCHAR(80) NOT NULL,
    model VARCHAR(160) NOT NULL,
    prompt TEXT NOT NULL,
    operation ENUM('text-to-image','image-edit') NOT NULL,
    size VARCHAR(80) NOT NULL,
    duration_ms BIGINT UNSIGNED NULL,
    cost DECIMAL(18,6) NULL,
    created_at DATETIME(3) NOT NULL,
    client_ip VARCHAR(120) NULL,
    user_agent VARCHAR(600) NULL,
    deleted_at DATETIME(3) NULL,
    UNIQUE KEY uq_app_history_generation_task (generation_task_id),
    KEY idx_app_history_owner_created (owner_user_id, created_at),
    KEY idx_app_history_client_created (client_id, created_at),
    KEY idx_app_history_deleted (deleted_at),
    CONSTRAINT fk_app_history_owner FOREIGN KEY (owner_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_history_images (
    id CHAR(36) NOT NULL PRIMARY KEY,
    history_id CHAR(36) NOT NULL,
    position_index INT UNSIGNED NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    width INT UNSIGNED NULL,
    height INT UNSIGNED NULL,
    mime_type VARCHAR(120) NULL,
    created_at DATETIME(3) NOT NULL,
    UNIQUE KEY uq_app_history_image_file (file_name),
    UNIQUE KEY uq_app_history_image_position (history_id, position_index),
    KEY idx_app_history_images_history (history_id),
    CONSTRAINT fk_app_history_images_history FOREIGN KEY (history_id) REFERENCES app_history_records(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_model_settings (
    provider VARCHAR(40) NOT NULL,
    model_id VARCHAR(160) NOT NULL,
    display_name VARCHAR(160) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    unit_credit_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by_user_id CHAR(36) NULL,
    PRIMARY KEY (provider, model_id),
    KEY idx_app_model_settings_enabled (enabled),
    KEY idx_app_model_settings_updated (updated_at),
    CONSTRAINT fk_app_model_settings_actor FOREIGN KEY (updated_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_announcements (
    id CHAR(36) NOT NULL PRIMARY KEY,
    title VARCHAR(80) NOT NULL,
    content VARCHAR(1200) NOT NULL,
    kind ENUM('info','warning','success') NOT NULL DEFAULT 'info',
    display_mode ENUM('topbar','popup') NOT NULL DEFAULT 'topbar',
    icon VARCHAR(40) NOT NULL DEFAULT 'megaphone',
    motion ENUM('none','shimmer','pulse','gradient') NOT NULL DEFAULT 'none',
    link_url VARCHAR(800) NULL,
    link_text VARCHAR(40) NULL,
    countdown_enabled TINYINT(1) NOT NULL DEFAULT 0,
    pinned TINYINT(1) NOT NULL DEFAULT 0,
    published TINYINT(1) NOT NULL DEFAULT 0,
    starts_at DATETIME(3) NULL,
    ends_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by_user_id CHAR(36) NULL,
    KEY idx_app_announcements_public (published, pinned, starts_at, ends_at, updated_at),
    CONSTRAINT fk_app_announcements_actor FOREIGN KEY (updated_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_gallery_submissions (
    id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    history_id CHAR(36) NOT NULL,
    image_id CHAR(36) NOT NULL,
    title VARCHAR(80) NOT NULL,
    description VARCHAR(500) NULL,
    show_prompt TINYINT(1) NOT NULL DEFAULT 0,
    status ENUM('pending','approved','rejected','withdrawn') NOT NULL DEFAULT 'pending',
    featured TINYINT(1) NOT NULL DEFAULT 0,
    rejection_reason VARCHAR(300) NULL,
    submitted_at DATETIME(3) NOT NULL,
    reviewed_at DATETIME(3) NULL,
    reviewed_by_user_id CHAR(36) NULL,
    updated_at DATETIME(3) NOT NULL,
    KEY idx_app_gallery_status (status, featured, submitted_at),
    KEY idx_app_gallery_user (user_id, submitted_at),
    KEY idx_app_gallery_history (history_id),
    KEY idx_app_gallery_image (image_id),
    CONSTRAINT fk_app_gallery_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_gallery_history FOREIGN KEY (history_id) REFERENCES app_history_records(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_gallery_image FOREIGN KEY (image_id) REFERENCES app_history_images(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_gallery_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_storage_settings (
    id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    enforcement_enabled TINYINT(1) NOT NULL DEFAULT 0,
    base_image_limit INT UNSIGNED NOT NULL DEFAULT 20,
    base_retention_days INT UNSIGNED NOT NULL DEFAULT 7,
    grace_days INT UNSIGNED NOT NULL DEFAULT 3,
    updated_at DATETIME(3) NOT NULL,
    updated_by_user_id CHAR(36) NULL,
    CONSTRAINT fk_app_storage_settings_actor FOREIGN KEY (updated_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `INSERT INTO app_storage_settings (
    id,
    enforcement_enabled,
    base_image_limit,
    base_retention_days,
    grace_days,
    updated_at,
    updated_by_user_id
  ) VALUES (
    1, 0, 20, 7, 3,
    UTC_TIMESTAMP(3),
    NULL
  )
  ON DUPLICATE KEY UPDATE id = id`,

  `CREATE TABLE IF NOT EXISTS app_storage_packages (
    id CHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    description VARCHAR(300) NULL,
    image_limit_bonus INT UNSIGNED NOT NULL DEFAULT 0,
    retention_days_bonus INT UNSIGNED NOT NULL DEFAULT 0,
    valid_days INT UNSIGNED NOT NULL,
    points_cost_cents BIGINT UNSIGNED NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INT UNSIGNED NOT NULL DEFAULT 100,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by_user_id CHAR(36) NULL,
    KEY idx_app_storage_packages_enabled (enabled, sort_order),
    CONSTRAINT fk_app_storage_packages_actor FOREIGN KEY (updated_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_storage_entitlements (
    id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    package_id CHAR(36) NULL,
    package_name VARCHAR(60) NOT NULL,
    image_limit_bonus INT UNSIGNED NOT NULL DEFAULT 0,
    retention_days_bonus INT UNSIGNED NOT NULL DEFAULT 0,
    points_cost_cents BIGINT UNSIGNED NOT NULL,
    purchased_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    credit_transaction_id CHAR(36) NULL,
    KEY idx_app_storage_entitlements_user (user_id, expires_at),
    KEY idx_app_storage_entitlements_package (package_id),
    CONSTRAINT fk_app_storage_entitlements_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_storage_entitlements_package FOREIGN KEY (package_id) REFERENCES app_storage_packages(id) ON DELETE SET NULL,
    CONSTRAINT fk_app_storage_entitlements_transaction FOREIGN KEY (credit_transaction_id) REFERENCES app_credit_transactions(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_user_groups (
    id CHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    description VARCHAR(300) NULL,
    sort_order INT UNSIGNED NOT NULL DEFAULT 100,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by_user_id CHAR(36) NULL,
    UNIQUE KEY uq_app_user_groups_name (name),
    KEY idx_app_user_groups_sort (sort_order, created_at),
    CONSTRAINT fk_app_user_groups_actor FOREIGN KEY (updated_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_user_group_members (
    group_id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    added_at DATETIME(3) NOT NULL,
    added_by_user_id CHAR(36) NULL,
    PRIMARY KEY (group_id, user_id),
    KEY idx_app_user_group_members_user (user_id, group_id),
    CONSTRAINT fk_app_user_group_members_group FOREIGN KEY (group_id) REFERENCES app_user_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_user_group_members_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_user_group_members_actor FOREIGN KEY (added_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_site_messages (
    id CHAR(36) NOT NULL PRIMARY KEY,
    title VARCHAR(80) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    kind ENUM('info','success','warning') NOT NULL DEFAULT 'info',
    target_type ENUM('all','group','user') NOT NULL DEFAULT 'all',
    target_group_id CHAR(36) NULL,
    target_user_id CHAR(36) NULL,
    delivered_count INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL,
    created_by_user_id CHAR(36) NULL,
    KEY idx_app_site_messages_created (created_at),
    KEY idx_app_site_messages_target_group (target_group_id),
    KEY idx_app_site_messages_target_user (target_user_id),
    CONSTRAINT fk_app_site_messages_group FOREIGN KEY (target_group_id) REFERENCES app_user_groups(id) ON DELETE SET NULL,
    CONSTRAINT fk_app_site_messages_user FOREIGN KEY (target_user_id) REFERENCES app_users(id) ON DELETE SET NULL,
    CONSTRAINT fk_app_site_messages_actor FOREIGN KEY (created_by_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_site_message_recipients (
    message_id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    read_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (message_id, user_id),
    KEY idx_app_site_message_recipients_user (user_id, read_at, created_at),
    CONSTRAINT fk_app_site_message_recipients_message FOREIGN KEY (message_id) REFERENCES app_site_messages(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_site_message_recipients_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_admin_audit_logs (
    id CHAR(36) NOT NULL PRIMARY KEY,
    actor_user_id CHAR(36) NULL,
    actor_username VARCHAR(32) NOT NULL,
    action VARCHAR(80) NOT NULL,
    target_type VARCHAR(80) NOT NULL,
    target_id VARCHAR(200) NULL,
    summary VARCHAR(500) NOT NULL,
    details_json JSON NULL,
    client_ip VARCHAR(120) NULL,
    user_agent VARCHAR(600) NULL,
    created_at DATETIME(3) NOT NULL,
    KEY idx_app_audit_created (created_at),
    KEY idx_app_audit_actor_created (actor_user_id, created_at),
    KEY idx_app_audit_action_created (action, created_at),
    CONSTRAINT fk_app_audit_actor FOREIGN KEY (actor_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_user_feedback (
    id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    type ENUM('suggestion','bug','question','other') NOT NULL DEFAULT 'suggestion',
    title VARCHAR(80) NOT NULL,
    content TEXT NOT NULL,
    status ENUM('open','processing','replied','closed') NOT NULL DEFAULT 'open',
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    last_replied_at DATETIME(3) NULL,
    KEY idx_app_feedback_user_updated (user_id, updated_at),
    KEY idx_app_feedback_status_updated (status, updated_at),
    CONSTRAINT fk_app_feedback_user FOREIGN KEY (user_id) REFERENCES app_users(id) ON DELETE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,

  `CREATE TABLE IF NOT EXISTS app_user_feedback_replies (
    id CHAR(36) NOT NULL PRIMARY KEY,
    feedback_id CHAR(36) NOT NULL,
    author_user_id CHAR(36) NULL,
    author_role ENUM('user','admin') NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    KEY idx_app_feedback_replies_feedback (feedback_id, created_at),
    KEY idx_app_feedback_replies_author (author_user_id),
    CONSTRAINT fk_app_feedback_reply_feedback FOREIGN KEY (feedback_id) REFERENCES app_user_feedback(id) ON DELETE CASCADE,
    CONSTRAINT fk_app_feedback_reply_author FOREIGN KEY (author_user_id) REFERENCES app_users(id) ON DELETE SET NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`

] as const;
